# -*- coding: utf-8 -*-
"""cwc25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hDfQ9tBcrZSKX5N19PpT5bgEhyvFIUda
"""

import pandas as pd
from io import StringIO

dados = """ID_jogo;Participante;Time_1;p_1;p_2;Time_2;mult
1;Abbade;Al Ahly;3;2;Inter Miami CF;1
1;Bueno;Al Ahly;0;1;Inter Miami CF;1
1;Gasparini;Al Ahly;2;2;Inter Miami CF;1
1;Gonzalez;Al Ahly;3;2;Inter Miami CF;1
1;Kim;Al Ahly;2;1;Inter Miami CF;1
2;Abbade;Bayern Munich;6;0;Auckland City;1
2;Bueno;Bayern Munich;6;0;Auckland City;1
2;Gasparini;Bayern Munich;6;0;Auckland City;1
2;Gonzalez;Bayern Munich;5;0;Auckland City;1
2;Kim;Bayern Munich;6;0;Auckland City;1
3;Abbade;Paris Saint-Germain;2;1;Atlético Madrid;1
3;Bueno;Paris Saint-Germain;1;1;Atlético Madrid;1
3;Gasparini;Paris Saint-Germain;4;2;Atlético Madrid;1
3;Gonzalez;Paris Saint-Germain;2;0;Atlético Madrid;1
3;Kim;Paris Saint-Germain;2;1;Atlético Madrid;1
4;Abbade;Palmeiras;0;0;Porto;1.5
4;Bueno;Palmeiras;0;2;Porto;1.5
4;Gasparini;Palmeiras;2;1;Porto;1.5
4;Gonzalez;Palmeiras;1;1;Porto;1.5
4;Kim;Palmeiras;1;1;Porto;1.5
5;Abbade;Botafogo;2;0;Seattle Sounders FC;1.5
5;Bueno;Botafogo;2;0;Seattle Sounders FC;1.5
5;Gasparini;Botafogo;2;0;Seattle Sounders FC;1.5
5;Gonzalez;Botafogo;2;1;Seattle Sounders FC;1.5
5;Kim;Botafogo;2;0;Seattle Sounders FC;1.5
6;Abbade;Chelsea;1;0;Los Angeles FC;1
6;Bueno;Chelsea;2;0;Los Angeles FC;1
6;Gasparini;Chelsea;3;0;Los Angeles FC;1
6;Gonzalez;Chelsea;3;1;Los Angeles FC;1
6;Kim;Chelsea;3;0;Los Angeles FC;1
7;Abbade;Boca Juniors;1;2;Benfica;1
7;Bueno;Boca Juniors;0;2;Benfica;1
7;Gasparini;Boca Juniors;1;2;Benfica;1
7;Gonzalez;Boca Juniors;1;1;Benfica;1
7;Kim;Boca Juniors;1;2;Benfica;1
8;Abbade;Flamengo;1;0;Espérance de Tunis;1.5
8;Bueno;Flamengo;2;0;Espérance de Tunis;1.5
8;Gasparini;Flamengo;2;1;Espérance de Tunis;1.5
8;Gonzalez;Flamengo;2;1;Espérance de Tunis;1.5
8;Kim;Flamengo;3;0;Espérance de Tunis;1.5
9;Abbade;Fluminense;0;0;Borussia Dortmund;1.5
9;Bueno;Fluminense;0;3;Borussia Dortmund;1.5
9;Gasparini;Fluminense;0;3;Borussia Dortmund;1.5
9;Gonzalez;Fluminense;1;2;Borussia Dortmund;1.5
9;Kim;Fluminense;1;3;Borussia Dortmund;1.5
10;Abbade;River Plate;1;0;Urawa Red Diamonds;1
10;Bueno;River Plate;2;0;Urawa Red Diamonds;1
10;Gasparini;River Plate;1;0;Urawa Red Diamonds;1
10;Gonzalez;River Plate;1;0;Urawa Red Diamonds;1
10;Kim;River Plate;2;1;Urawa Red Diamonds;1
11;Abbade;Ulsan HD;0;1;Mamelodi Sundowns;1
11;Bueno;Ulsan HD;0;0;Mamelodi Sundowns;1
11;Gasparini;Ulsan HD;2;3;Mamelodi Sundowns;1
11;Gonzalez;Ulsan HD;0;1;Mamelodi Sundowns;1
11;Kim;Ulsan HD;2;0;Mamelodi Sundowns;1
12;Abbade;Monterrey;0;1;Inter Milan;1
12;Bueno;Monterrey;0;1;Inter Milan;1
12;Gasparini;Monterrey;1;3;Inter Milan;1
12;Gonzalez;Monterrey;0;2;Inter Milan;1
12;Kim;Monterrey;0;3;Inter Milan;1
13;Abbade;Manchester City;2;0;Wydad AC;1
13;Bueno;Manchester City;3;0;Wydad AC;1
13;Gasparini;Manchester City;4;0;Wydad AC;1
13;Gonzalez;Manchester City;3;0;Wydad AC;1
13;Kim;Manchester City;4;0;Wydad AC;1
14;Abbade;Real Madrid;2;0;Al-Hilal;1
14;Bueno;Real Madrid;3;0;Al-Hilal;1
14;Gasparini;Real Madrid;3;2;Al-Hilal;1
14;Gonzalez;Real Madrid;3;1;Al-Hilal;1
14;Kim;Real Madrid;3;1;Al-Hilal;1
15;Abbade;Pachuca;1;0;Red Bull Salzburg;1
15;Bueno;Pachuca;0;2;Red Bull Salzburg;1
15;Gasparini;Pachuca;1;1;Red Bull Salzburg;1
15;Gonzalez;Pachuca;1;0;Red Bull Salzburg;1
15;Kim;Pachuca;2;2;Red Bull Salzburg;1
16;Abbade;Al Ain;0;1;Juventus;1
16;Bueno;Al Ain;1;1;Juventus;1
16;Gasparini;Al Ain;0;2;Juventus;1
16;Gonzalez;Al Ain;1;2;Juventus;1
16;Kim;Al Ain;0;3;Juventus;1
17;Abbade;Al Ahly;1;2;Palmeiras;1.5
17;Bueno;Al Ahly;1;1;Palmeiras;1.5
17;Gasparini;Al Ahly;0;1;Palmeiras;1.5
17;Gonzalez;Al Ahly;1;2;Palmeiras;1.5
17;Kim;Al Ahly;0;2;Palmeiras;1.5
18;Abbade;Porto;2;0;Inter Miami CF;1
18;Bueno;Porto;3;0;Inter Miami CF;1
18;Gasparini;Porto;3;1;Inter Miami CF;1
18;Gonzalez;Porto;2;0;Inter Miami CF;1
18;Kim;Porto;2;1;Inter Miami CF;1
19;Abbade;Seattle Sounders FC;0;3;Atlético Madrid;1
19;Bueno;Seattle Sounders FC;0;3;Atlético Madrid;1
19;Gasparini;Seattle Sounders FC;0;2;Atlético Madrid;1
19;Gonzalez;Seattle Sounders FC;0;2;Atlético Madrid;1
19;Kim;Seattle Sounders FC;0;2;Atlético Madrid;1
20;Abbade;Paris Saint-Germain;4;1;Botafogo;1.5
20;Bueno;Paris Saint-Germain;5;0;Botafogo;1.5
20;Gasparini;Paris Saint-Germain;3;0;Botafogo;1.5
20;Gonzalez;Paris Saint-Germain;3;0;Botafogo;1.5
20;Kim;Paris Saint-Germain;3;1;Botafogo;1.5
21;Abbade;Benfica;3;0;Auckland City;1
21;Bueno;Benfica;3;0;Auckland City;1
21;Gasparini;Benfica;3;0;Auckland City;1
21;Gonzalez;Benfica;3;0;Auckland City;1
21;Kim;Benfica;3;0;Auckland City;1
22;Abbade;Chelsea;1;0;Flamengo;1.5
22;Bueno;Chelsea;2;0;Flamengo;1.5
22;Gasparini;Chelsea;3;1;Flamengo;1.5
22;Gonzalez;Chelsea;2;1;Flamengo;1.5
22;Kim;Chelsea;2;1;Flamengo;1.5
23;Abbade;Espérance de Tunis;1;1;Los Angeles FC;1
23;Bueno;Espérance de Tunis;1;1;Los Angeles FC;1
23;Gasparini;Espérance de Tunis;1;2;Los Angeles FC;1
23;Gonzalez;Espérance de Tunis;0;1;Los Angeles FC;1
23;Kim;Espérance de Tunis;1;1;Los Angeles FC;1
24;Abbade;Bayern Munich;2;0;Boca Juniors;1
24;Bueno;Bayern Munich;2;0;Boca Juniors;1
24;Gasparini;Bayern Munich;4;1;Boca Juniors;1
24;Gonzalez;Bayern Munich;3;1;Boca Juniors;1
24;Kim;Bayern Munich;3;0;Boca Juniors;1
25;Abbade;Mamelodi Sundowns;0;2;Borussia Dortmund;1
25;Bueno;Mamelodi Sundowns;0;4;Borussia Dortmund;1
25;Gasparini;Mamelodi Sundowns;0;3;Borussia Dortmund;1
25;Gonzalez;Mamelodi Sundowns;0;2;Borussia Dortmund;1
25;Kim;Mamelodi Sundowns;0;3;Borussia Dortmund;1
26;Abbade;Inter Milan;2;0;Urawa Red Diamonds;1
26;Bueno;Inter Milan;2;1;Urawa Red Diamonds;1
26;Gasparini;Inter Milan;2;0;Urawa Red Diamonds;1
26;Gonzalez;Inter Milan;2;1;Urawa Red Diamonds;1
26;Kim;Inter Milan;4;0;Urawa Red Diamonds;1
27;Abbade;Fluminense;2;0;Ulsan HD;1.5
27;Bueno;Fluminense;1;1;Ulsan HD;1.5
27;Gasparini;Fluminense;3;1;Ulsan HD;1.5
27;Gonzalez;Fluminense;2;0;Ulsan HD;1.5
27;Kim;Fluminense;1;0;Ulsan HD;1.5
28;Abbade;River Plate;1;1;Monterrey;1
28;Bueno;River Plate;1;0;Monterrey;1
28;Gasparini;River Plate;2;2;Monterrey;1
28;Gonzalez;River Plate;0;0;Monterrey;1
28;Kim;River Plate;1;0;Monterrey;1
29;Abbade;Juventus;1;0;Wydad AC;1
29;Bueno;Juventus;1;0;Wydad AC;1
29;Gasparini;Juventus;2;1;Wydad AC;1
29;Gonzalez;Juventus;2;1;Wydad AC;1
29;Kim;Juventus;2;1;Wydad AC;1
30;Abbade;Real Madrid;1;0;Pachuca;1
30;Bueno;Real Madrid;4;1;Pachuca;1
30;Gasparini;Real Madrid;3;0;Pachuca;1
30;Gonzalez;Real Madrid;2;0;Pachuca;1
30;Kim;Real Madrid;3;0;Pachuca;1
31;Abbade;Red Bull Salzburg;1;1;Al-Hilal;1
31;Bueno;Red Bull Salzburg;2;1;Al-Hilal;1
31;Gasparini;Red Bull Salzburg;1;2;Al-Hilal;1
31;Gonzalez;Red Bull Salzburg;1;2;Al-Hilal;1
31;Kim;Red Bull Salzburg;1;2;Al-Hilal;1
32;Abbade;Manchester City;2;0;Al Ain;1
32;Bueno;Manchester City;4;0;Al Ain;1
32;Gasparini;Manchester City;3;1;Al Ain;1
32;Gonzalez;Manchester City;3;0;Al Ain;1
32;Kim;Manchester City;2;0;Al Ain;1
33;Abbade;Seattle Sounders FC;0;4;Paris Saint-Germain;1
33;Bueno;Seattle Sounders FC;0;4;Paris Saint-Germain;1
33;Gasparini;Seattle Sounders FC;1;3;Paris Saint-Germain;1
33;Gonzalez;Seattle Sounders FC;0;4;Paris Saint-Germain;1
33;Kim;Seattle Sounders FC;0;3;Paris Saint-Germain;1
34;Abbade;Atlético Madrid;1;0;Botafogo;1.5
34;Bueno;Atlético Madrid;3;0;Botafogo;1.5
34;Gasparini;Atlético Madrid;1;0;Botafogo;1.5
34;Gonzalez;Atlético Madrid;1;1;Botafogo;1.5
34;Kim;Atlético Madrid;2;0;Botafogo;1.5
35;Abbade;Porto;1;0;Al Ahly;1
35;Bueno;Porto;2;0;Al Ahly;1
35;Gasparini;Porto;2;1;Al Ahly;1
35;Gonzalez;Porto;1;0;Al Ahly;1
35;Kim;Porto;2;1;Al Ahly;1
36;Abbade;Inter Miami CF;0;1;Palmeiras;1.5
36;Bueno;Inter Miami CF;1;2;Palmeiras;1.5
36;Gasparini;Inter Miami CF;0;2;Palmeiras;1.5
36;Gonzalez;Inter Miami CF;1;2;Palmeiras;1.5
36;Kim;Inter Miami CF;1;3;Palmeiras;1.5
37;Abbade;Auckland City;0;2;Boca Juniors;1
37;Bueno;Auckland City;0;1;Boca Juniors;1
37;Gasparini;Auckland City;1;2;Boca Juniors;1
37;Gonzalez;Auckland City;0;2;Boca Juniors;1
37;Kim;Auckland City;0;2;Boca Juniors;1
38;Abbade;Benfica;1;2;Bayern Munich;1
38;Bueno;Benfica;2;3;Bayern Munich;1
38;Gasparini;Benfica;1;3;Bayern Munich;1
38;Gonzalez;Benfica;1;2;Bayern Munich;1
38;Kim;Benfica;1;2;Bayern Munich;1
39;Abbade;Espérance de Tunis;0;2;Chelsea;1
39;Bueno;Espérance de Tunis;0;3;Chelsea;1
39;Gasparini;Espérance de Tunis;0;3;Chelsea;1
39;Gonzalez;Espérance de Tunis;0;2;Chelsea;1
39;Kim;Espérance de Tunis;0;3;Chelsea;1
40;Abbade;Los Angeles FC;1;3;Flamengo;1.5
40;Bueno;Los Angeles FC;1;2;Flamengo;1.5
40;Gasparini;Los Angeles FC;2;3;Flamengo;1.5
40;Gonzalez;Los Angeles FC;1;2;Flamengo;1.5
40;Kim;Los Angeles FC;2;2;Flamengo;1.5
41;Abbade;Borussia Dortmund;1;0;Ulsan HD;1
41;Bueno;Borussia Dortmund;2;0;Ulsan HD;1
41;Gasparini;Borussia Dortmund;4;1;Ulsan HD;1
41;Gonzalez;Borussia Dortmund;3;0;Ulsan HD;1
41;Kim;Borussia Dortmund;3;0;Ulsan HD;1
42;Abbade;Mamelodi Sundowns;0;1;Fluminense;1.5
42;Bueno;Mamelodi Sundowns;0;1;Fluminense;1.5
42;Gasparini;Mamelodi Sundowns;2;2;Fluminense;1.5
42;Gonzalez;Mamelodi Sundowns;1;2;Fluminense;1.5
42;Kim;Mamelodi Sundowns;0;2;Fluminense;1.5
43;Abbade;Urawa Red Diamonds;1;2;Monterrey;1
43;Bueno;Urawa Red Diamonds;1;1;Monterrey;1
43;Gasparini;Urawa Red Diamonds;1;1;Monterrey;1
43;Gonzalez;Urawa Red Diamonds;1;1;Monterrey;1
43;Kim;Urawa Red Diamonds;0;0;Monterrey;1
44;Abbade;Inter Milan;1;0;River Plate;1
44;Bueno;Inter Milan;2;2;River Plate;1
44;Gasparini;Inter Milan;4;2;River Plate;1
44;Gonzalez;Inter Milan;1;0;River Plate;1
44;Kim;Inter Milan;2;2;River Plate;1
45;Abbade;Juventus;1;1;Manchester City;1
45;Bueno;Juventus;0;2;Manchester City;1
45;Gasparini;Juventus;1;3;Manchester City;1
45;Gonzalez;Juventus;1;2;Manchester City;1
45;Kim;Juventus;1;2;Manchester City;1
46;Abbade;Wydad AC;1;0;Al Ain;1
46;Bueno;Wydad AC;0;0;Al Ain;1
46;Gasparini;Wydad AC;2;1;Al Ain;1
46;Gonzalez;Wydad AC;1;1;Al Ain;1
46;Kim;Wydad AC;1;0;Al Ain;1
47;Abbade;Al-Hilal;1;0;Pachuca;1
47;Bueno;Al-Hilal;1;1;Pachuca;1
47;Gasparini;Al-Hilal;2;1;Pachuca;1
47;Gonzalez;Al-Hilal;2;2;Pachuca;1
47;Kim;Al-Hilal;2;1;Pachuca;1
48;Abbade;Red Bull Salzburg;0;2;Real Madrid;1
48;Bueno;Red Bull Salzburg;2;3;Real Madrid;1
48;Gasparini;Red Bull Salzburg;2;4;Real Madrid;1
48;Gonzalez;Red Bull Salzburg;0;3;Real Madrid;1
48;Kim;Red Bull Salzburg;0;3;Real Madrid;1
"""

# Converter a string para DataFrame
palpites = pd.read_csv(StringIO(dados), sep=';')

# Visualizar as primeiras linhas
palpites.head(10)

import pandas as pd

url = "https://en.wikipedia.org/wiki/2025_FIFA_Club_World_Cup"
tables = pd.read_html(url)

header_rows = []

for i, table in enumerate(tables):
    if table.shape[1] >= 3:
        second_col_name = str(table.columns[1])
        if "–" in second_col_name:
            # Pega só as 3 primeiras colunas do header para garantir
            header_rows.append(list(table.columns[:3]))

# Cria DataFrame com essas linhas
results = pd.DataFrame(header_rows, columns=['Time_1', 'p', 'Time_2'])

# Faz o split na coluna 'p' em duas colunas 'p_1' e 'p_2'
results[['gols_t_1', 'gols_t_2']] = results['p'].str.split('–', expand=True)

# Se quiser, pode remover a coluna original 'p'
results = results.drop(columns=['p'])

# Reordena as colunas
results = results[['Time_1', 'gols_t_1', 'Time_2', 'gols_t_2']]

results.head(48)

!pip install pandasql
from pandasql import sqldf

# Função para facilitar a execução
pysqldf = lambda q: sqldf(q, globals())

query = """
SELECT
  p.*,
  CASE WHEN (p.Time_1 = r.Time_1 AND p.Time_2 = r.Time_2) THEN r.gols_t_1 ELSE r.gols_t_2 END AS gols_t_1,
  CASE WHEN (p.Time_1 = r.Time_1 AND p.Time_2 = r.Time_2) THEN r.gols_t_2 ELSE r.gols_t_1 END AS gols_t_2

FROM palpites p
LEFT JOIN results r
ON (p.Time_1 = r.Time_1 AND p.Time_2 = r.Time_2) OR (p.Time_1 = r.Time_2 AND p.Time_2 = r.Time_1)
"""

tab = pysqldf(query)
tab.head(1000)

query = """
SELECT
  *,
  CASE
    WHEN p_1 = gols_t_1 AND p_2 = gols_t_2 THEN 6 * mult
    WHEN
      ((p_1 > p_2 AND gols_t_1 > gols_t_2) OR (p_1 < p_2 AND gols_t_1 < gols_t_2) OR (p_1 = p_2 AND gols_t_1 = gols_t_2))
      AND (p_1 - p_2 = gols_t_1 - gols_t_2)
      THEN 3 * mult
    WHEN
      ((p_1 > p_2 AND gols_t_1 > gols_t_2) OR (p_1 < p_2 AND gols_t_1 < gols_t_2))
      AND (p_1 - p_2 <> gols_t_1 - gols_t_2)
      THEN 2 * mult
    ELSE 0
  END AS pontuacao
  ,CASE
    WHEN p_1 = gols_t_1 AND p_2 = gols_t_2 THEN 1 ELSE 0 END AS cravada
FROM tab
"""

tab_final = pysqldf(query)
tab_final.head(1000)

query = """
SELECT
participante
,sum(pontuacao) as pontuacao
,sum(cravada) as cravada

from tab_final
group by participante
order by pontuacao desc, cravada desc
"""

RANKING = pysqldf(query)
RANKING['pontuacao'] = RANKING['pontuacao'].astype(float).apply(lambda x: int(x) if x.is_integer() else x)
RANKING.head(50)

RANKING_texto = RANKING
RANKING_texto['pontuacao'] = RANKING_texto['pontuacao'].apply(lambda x: f'{x:g}')
RANKING_texto.head(50)

query = """
SELECT distinct
  UPPER(Time_1 || " X " || Time_2) AS Time_Concat
FROM tab_final
WHERE gols_t_1 IS NOT NULL
  AND ID_jogo = (SELECT MAX(ID_jogo) FROM tab_final WHERE gols_t_1 IS NOT NULL)
"""
pysqldf(query).iloc[0, 0]

# Supondo que você já tenha o DataFrame RANKING e a string jogo_texto, ex:

query = """
SELECT distinct
  UPPER(Time_1 || " X " || Time_2 || "*") AS Time_Concat
FROM tab_final
WHERE gols_t_1 IS NOT NULL
  AND ID_jogo = (SELECT MAX(ID_jogo) FROM tab_final WHERE gols_t_1 IS NOT NULL)
"""

# jogo
jogo_texto = pysqldf(query).iloc[0, 0]

# valores
def formatar_ranking(ranking_df, jogo):
    linhas = [f"*RANKING APÓS {jogo}\n"]
    for i, row in ranking_df.head(5).iterrows():
        linhas.append(f"{i+1}) {row['Participante']}: {row['pontuacao']} ({row['cravada']} cravadas)")
    return "\n".join(linhas)

texto_formatado = formatar_ranking(RANKING_texto, jogo_texto)
print(texto_formatado)

# Instalar bibliotecas necessárias
!pip install twilio

from twilio.rest import Client

account_sid = 'ACf40fde2144935f3c4cb67498d9c5bd6a'
auth_token = '73f86d2fc5c1f6cb5592164cd6056d38'
client = Client(account_sid, auth_token)

message = client.messages.create(
  from_='whatsapp:+14155238886',
  body=texto_formatado,
  to='whatsapp:+5521982631104'
)

print(message.sid)